# Generated by Django 5.1.15 on 2026-09-13 15:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnToStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Số kg mang về')),
                ('left_warehouse_at', models.DateTimeField(blank=True, null=True, verbose_name='Giờ rời kho')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Giờ về kho')),
                ('decision', models.CharField(choices=[('PENDING', 'Chờ quyết định'), ('RESTOCK', 'Tái nhập'), ('WRITE_OFF', 'Huỷ bỏ (hạch toán lỗ)')], default='PENDING', max_length=10, verbose_name='Quyết định')),
                ('status', models.CharField(choices=[('DRAFT', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt')], default='DRAFT', max_length=10, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hàng hoàn về kho',
                'verbose_name_plural': 'Hàng hoàn về kho',
                'ordering': ['-created_at', '-id'],
                'permissions': [('approve_returntostock', 'Duyệt hàng hoàn về kho')],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('MATERIAL_RECEIPT', 'Nhập vật tư'), ('ADJUSTMENT', 'Điều chỉnh')], max_length=20, verbose_name='Mục đích')),
                ('qty_change', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Biến động (kg)')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phiếu điều chỉnh kho',
                'verbose_name_plural': 'Phiếu điều chỉnh kho',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Nhập lô'), ('SALE', 'Bán ra'), ('RETURN_RESTOCK', 'Hàng hoàn tái nhập'), ('RECONCILE', 'Điều chỉnh kiểm kê'), ('WRITE_OFF', 'Hạch toán lỗ / huỷ'), ('CANCEL_RESTORE', 'Hoàn kho do huỷ đơn')], max_length=16, verbose_name='Loại')),
                ('qty_change', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Biến động (kg)')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Chứng từ nguồn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chuyển động kho',
                'verbose_name_plural': 'Sổ chuyển động kho',
                'ordering': ['-created_at', '-id'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='StockReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField(verbose_name='Ngày kiểm kê')),
                ('status', models.CharField(choices=[('DRAFT', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt')], default='DRAFT', max_length=10, verbose_name='Trạng thái')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm duyệt')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phiếu kiểm kê',
                'verbose_name_plural': 'Phiếu kiểm kê',
                'ordering': ['-count_date', '-id'],
                'permissions': [('approve_stockreconciliation', 'Duyệt kiểm kê')],
            },
        ),
        migrations.CreateModel(
            name='StockReconciliationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=3, help_text='Tồn sổ tại thời điểm nhập số.', max_digits=12, verbose_name='Tồn sổ (ảnh chụp)')),
                ('counted_qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Tồn thực đếm (kg)')),
                ('difference_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Chênh lệch (kg)')),
                ('reason', models.TextField(blank=True, help_text='Bắt buộc khi chênh lệch dương (BR-KK-04).', verbose_name='Lý do')),
            ],
            options={
                'verbose_name': 'Dòng kiểm kê',
                'verbose_name_plural': 'Dòng kiểm kê',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên kho')),
                ('is_group', models.BooleanField(default=False, verbose_name='Là nhóm kho')),
            ],
            options={
                'verbose_name': 'Kho',
                'verbose_name_plural': 'Kho',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=40, unique=True, verbose_name='Mã lô')),
                ('received_date', models.DateField(verbose_name='Ngày nhập')),
                ('expiry_date', models.DateField(verbose_name='Hạn dùng')),
                ('qty_received', models.DecimalField(decimal_places=3, help_text='Mẫu số tính landed_unit_cost — KHÔNG đổi khi có hao hụt (BR-GV-01).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Số kg nhập ban đầu')),
                ('qty_available', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tồn sổ (kg)')),
                ('qty_reserved', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text="Tổng kg đang bị đơn 'giữ chỗ' khoá (BR-BH-02).", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đang giữ chỗ (kg)')),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Đơn giá mua (đ/kg)')),
                ('landed_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='(giá mua lô + chi phí phân bổ) / qty_received. Đổi phải ghi AuditLog (BR-GV-03).', max_digits=14, verbose_name='Giá vốn lô (đ/kg)')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SELLING', 'Đang bán'), ('NEAR_EXPIRY', 'Cận hạn'), ('SOLD_OUT', 'Hết hàng'), ('EXPIRED', 'Quá hạn'), ('CANCELLED', 'Đã huỷ'), ('CLOSED', 'Đã chốt')], default='DRAFT', max_length=12, verbose_name='Trạng thái')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm chốt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_batches', to=settings.AUTH_USER_MODEL, verbose_name='Người chốt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.item', verbose_name='Mặt hàng')),
            ],
            options={
                'verbose_name': 'Lô hàng',
                'verbose_name_plural': 'Lô hàng',
                'ordering': ['received_date', 'id'],
                'permissions': [('publish_batch', 'Publish lô ra Shop'), ('close_batch', 'Chốt lô (đông cứng lãi/lỗ)'), ('view_costprice', 'Xem giá vốn / đơn giá mua')],
            },
        ),
    ]
