# Generated by Django 5.1.15 on 2026-09-13 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0002_initial'),
        ('inventory', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='purchasing.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='returntostock',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='returntostock',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.batch', verbose_name='Lô gốc'),
        ),
        migrations.AddField(
            model_name='returntostock',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_created', to=settings.AUTH_USER_MODEL, verbose_name='Người ghi nhận'),
        ),
        migrations.AddField(
            model_name='returntostock',
            name='delivery_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='delivery.deliverynote', verbose_name='Phiếu giao liên quan'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='inventory.batch', verbose_name='Lô'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.batch', verbose_name='Lô'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Người/Hệ thống'),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations_created', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập số'),
        ),
        migrations.AddField(
            model_name='stockreconciliationline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_lines', to='inventory.batch', verbose_name='Lô'),
        ),
        migrations.AddField(
            model_name='stockreconciliationline',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockreconciliation', verbose_name='Phiếu kiểm kê'),
        ),
        migrations.AddField(
            model_name='batch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.warehouse', verbose_name='Kho'),
        ),
    ]
