# Generated by Django 5.1.15 on 2026-09-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['received_date', 'id'], 'permissions': [('publish_batch', 'Publish lô ra Shop'), ('close_batch', 'Chốt lô (đông cứng lãi/lỗ)'), ('view_costprice', 'Xem giá vốn / đơn giá mua'), ('cancel_expired_batch', 'Huỷ lô quá hạn (hạch toán lỗ)')], 'verbose_name': 'Lô hàng', 'verbose_name_plural': 'Lô hàng'},
        ),
    ]
