# Generated by Django 5.1.15 on 2026-09-30 10:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_batch_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledgerentry',
            name='movement_type',
            field=models.CharField(choices=[('RECEIPT', 'Nhập lô'), ('SALE', 'Bán ra'), ('RETURN_RESTOCK', 'Hàng hoàn tái nhập'), ('RECONCILE', 'Điều chỉnh kiểm kê'), ('WRITE_OFF', 'Hạch toán lỗ / huỷ'), ('CANCEL_RESTORE', 'Hoàn kho do huỷ đơn'), ('SUPPLIER_RETURN', 'Trả nhà cung cấp')], max_length=16, verbose_name='Loại'),
        ),
        migrations.CreateModel(
            name='BatchSupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Số kg trả NCC')),
                ('supplier_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tiền NCC hoàn')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú')),
                ('request_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Mã yêu cầu (chống gửi lặp)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='inventory.batch', verbose_name='Lô')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận')),
            ],
            options={
                'verbose_name': 'Trả NCC lô quá hạn',
                'verbose_name_plural': 'Trả NCC lô quá hạn',
                'default_permissions': ('view',),
            },
        ),
    ]
