# Generated by Django 5.1.15 on 2026-10-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockreconciliation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreconciliation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt')], default='DRAFT', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
