# Generated by Django 5.1.15 on 2026-10-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stocktake_submitted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returntostock',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('CANCELLED', 'Đã huỷ')], default='DRAFT', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
