# Generated by Django 5.1.15 on 2026-10-02 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_grant_add_returntostock_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returntostock',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Xoá lúc'),
        ),
        migrations.AddField(
            model_name='returntostock',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá'),
        ),
    ]
