# Generated by Django 5.1.15 on 2026-10-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_returntostock_soft_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['received_date', 'id'], 'permissions': [('publish_batch', 'Mở bán lô'), ('close_batch', 'Chốt lô (đông cứng lãi/lỗ)'), ('view_costprice', 'Xem giá vốn / đơn giá mua'), ('cancel_expired_batch', 'Huỷ lô quá hạn (ghi lỗ)')], 'verbose_name': 'Lô hàng', 'verbose_name_plural': 'Lô hàng'},
        ),
        migrations.AlterModelOptions(
            name='batchsupplierreturn',
            options={'default_permissions': ('view',), 'verbose_name': 'Trả nhà cung cấp', 'verbose_name_plural': 'Trả nhà cung cấp'},
        ),
        migrations.AlterModelOptions(
            name='returntostock',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('approve_returntostock', 'Duyệt hàng hoàn')], 'verbose_name': 'Hàng hoàn', 'verbose_name_plural': 'Hàng hoàn'},
        ),
        migrations.AlterModelOptions(
            name='stockentry',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Phiếu điều chỉnh tồn', 'verbose_name_plural': 'Phiếu điều chỉnh tồn'},
        ),
        migrations.AlterField(
            model_name='returntostock',
            name='decision',
            field=models.CharField(choices=[('PENDING', 'Chờ quyết định'), ('RESTOCK', 'Tái nhập'), ('WRITE_OFF', 'Huỷ hàng, ghi lỗ')], default='PENDING', max_length=10, verbose_name='Quyết định'),
        ),
        migrations.AlterField(
            model_name='stockledgerentry',
            name='movement_type',
            field=models.CharField(choices=[('RECEIPT', 'Nhập lô'), ('SALE', 'Bán ra'), ('RETURN_RESTOCK', 'Hàng hoàn tái nhập'), ('RECONCILE', 'Điều chỉnh kiểm kê'), ('WRITE_OFF', 'Huỷ hàng, ghi lỗ'), ('CANCEL_RESTORE', 'Hoàn kho do huỷ đơn'), ('SUPPLIER_RETURN', 'Trả nhà cung cấp')], max_length=16, verbose_name='Loại'),
        ),
    ]
