# Smoke trên BE THẬT (Lô 3 Đơn & tiền): cần BE chạy ở :8000 có seed_demo + user loc/ql1 (mật khẩu Songbien2026), console build NEXT_PUBLIC_USE_MOCK=0
# phục vụ ở :3102. Mỗi lần chạy tiêu thụ đơn Giữ chỗ demo, nên chạy lại cần nạp lại DB.
import re, sys
from playwright.sync_api import expect, sync_playwright
BASE="http://127.0.0.1:3102"; R=[]
expect.set_options(timeout=15000)
def ok(n,c,e=""): R.append((n,bool(c),e)); print("PASS" if c else "FAIL", n, "" if c else e)
with sync_playwright() as p:
    b=p.chromium.launch(); errs=[]; reqs=[]
    ctx=b.new_context(viewport={"width":1280,"height":900},reduced_motion="reduce"); page=ctx.new_page()
    page.on("console", lambda m: m.type=="error" and errs.append(m.text))
    page.on("response", lambda r: "/api/" in r.url and reqs.append((r.request.method, r.url.split("/api/")[1], r.status)))
    page.goto(BASE+"/login/"); page.wait_for_load_state("networkidle")
    page.get_by_label("Tài khoản").fill("loc"); page.get_by_label("Mật khẩu").fill("Songbien2026"); page.get_by_role("button",name="Đăng nhập").click()
    page.wait_for_selector(".nav a", state="attached")
    page.goto(BASE+"/orders/"); page.wait_for_load_state("networkidle")
    expect(page.locator("tbody tr").first).to_be_visible()
    rows=page.locator("tbody tr"); n=rows.count()
    ok("BE thật: danh sách đơn có dữ liệu demo (6 đơn)", n==6, str(n))
    heads=[h.strip() for h in page.locator("thead th").all_inner_texts()]
    ok("BE thật: cột đúng", heads==["Mã đơn","Khách hàng","Trạng thái","Giao hàng","Lý do","Tổng tiền","Thời gian"], str(heads))
    body=page.locator("tbody").inner_text()
    ok("BE thật: có chip Giữ chỗ / Đang xử lý / Đã huỷ + lý do Hết giờ giữ chỗ", all(x in body for x in ["Giữ chỗ","Đang xử lý","Đã huỷ","Hết giờ giữ chỗ"]), body[:300])
    page.screenshot(path="/tmp/shots3-real3-list.png")
    # chi tiết đơn Giữ chỗ
    page.locator("tbody tr").filter(has=page.locator("td", has_text=re.compile(r"^\s*Giữ chỗ\s*$"))).first.click()
    page.wait_for_url(re.compile(r"/orders/detail/\?id=\d+$"))
    expect(page.locator("main header h2")).to_be_visible(); page.wait_for_load_state("networkidle")
    hb=[t.strip() for t in page.locator("main header .btn").all_inner_texts() if t.strip()]
    ok("BE thật: đơn Giữ chỗ → nút chính 'Xác nhận đã nhận tiền'", hb[:1]==["Xác nhận đã nhận tiền"], str(hb))
    txt=page.locator("main").inner_text()
    ok("BE thật: chi tiết có SĐT đủ, 'Còn giữ chỗ' mm:ss, StatusPath", re.search(r"0\d{9}",txt) and re.search(r"\d{2}:\d{2}",txt) and "Giữ chỗ" in txt, txt[:200])
    page.screenshot(path="/tmp/shots3-real3-detail.png")
    oid=re.search(r"id=(\d+)",page.url).group(1)
    page.get_by_role("button",name="Xác nhận đã nhận tiền").click()
    d=page.get_by_role("dialog",name="Xác nhận đã nhận tiền"); expect(d).to_be_visible()
    d.get_by_label("Mã giao dịch ngân hàng").fill("FT-R3-"+__import__("uuid").uuid4().hex[:8])
    d.locator("button[type=submit]").click()
    expect(page.locator(".toast-item").last).to_be_visible(); page.wait_for_load_state("networkidle")
    ok("BE thật: xác nhận đã nhận tiền → toast + chip đổi, hết nút", "Giữ chỗ" not in page.locator("main header").inner_text() and page.get_by_role("button",name="Xác nhận đã nhận tiền").count()==0, page.locator("main header").inner_text())
    ok("BE thật: POST confirm-payment trả 200/201", any(m=="POST" and "confirm-payment" in u and s in (200,201) for m,u,s in reqs), str([x for x in reqs if x[0]=="POST"]))
    # lập hoàn: đơn đã thanh toán đang xử lý → huỷ
    ok("BE thật: 'Huỷ đơn' xuất hiện sau khi đã thanh toán", page.get_by_role("button",name="Huỷ đơn").count()>=1, str([t for t in page.locator("main header .btn").all_inner_texts()]))
    page.get_by_role("button",name="Huỷ đơn").first.click()
    d=page.get_by_role("dialog",name="Huỷ đơn"); d.get_by_label("Lý do huỷ").select_option(label="Khách đổi ý"); d.locator("button[type=submit]").click()
    d2=page.get_by_role("dialog",name="Huỷ đơn này?"); d2.locator("button[type=submit]").click()
    expect(page.locator("main header")).to_contain_text("Đã huỷ"); page.wait_for_load_state("networkidle")
    ok("BE thật: huỷ đơn → Đã huỷ", True)
    page.get_by_role("button",name=re.compile("Lập phiếu hoàn")).first.click()
    d=page.get_by_role("dialog",name="Lập phiếu hoàn"); expect(d).to_be_visible()
    d.locator("button[type=submit]").click()
    expect(page.locator(".toast-item").last).to_contain_text("Đã lập phiếu hoàn")
    ok("BE thật: lập phiếu hoàn từ đơn → toast", any(m=="POST" and "refunds/create" in u and s in (200,201) for m,u,s in reqs), str([x for x in reqs if "refund" in x[1]]))
    # phiếu hoàn
    page.goto(BASE+"/orders/refunds/"); page.wait_for_load_state("networkidle")
    expect(page.locator("tbody tr").first).to_be_visible()
    ok("BE thật: tab Phiếu hoàn có phiếu Chờ hoàn", "Chờ hoàn" in page.locator("tbody").inner_text())
    page.locator("tbody tr", has_text="Chờ hoàn").first.click()
    page.wait_for_url(re.compile(r"/orders/refunds/detail/\?id=\d+$")); expect(page.locator("main header h2")).to_be_visible(); page.wait_for_load_state("networkidle")
    ok("BE thật: chi tiết phiếu hoàn có 'Xác nhận đã hoàn'", page.get_by_role("button",name=re.compile("^Xác nhận đã hoàn")).count()==1)
    page.get_by_role("button",name=re.compile("^Xác nhận đã hoàn")).first.click()
    d=page.get_by_role("dialog",name="Xác nhận đã hoàn tiền"); d.get_by_label("Mã giao dịch chuyển khoản hoàn").fill("HT-R3-"+__import__("uuid").uuid4().hex[:8]); d.locator("button[type=submit]").click()
    expect(page.locator("main header")).to_contain_text("Đã hoàn")
    ok("BE thật: xác nhận hoàn → Đã hoàn", True)
    page.goto(BASE+"/orders/payments/"); page.wait_for_load_state("networkidle")
    ok("BE thật: hàng chờ thanh toán tải được (rỗng hoặc có dòng)", page.get_by_text("Không còn khoản tiền nào chờ xử lý").count()==1 or page.locator("tbody tr").count()>0)
    page.goto(BASE+"/orders/detail/?id=999999"); page.wait_for_load_state("networkidle")
    expect(page.get_by_text(re.compile("Không tìm thấy|không tồn tại|không có quyền"))).to_be_visible()
    ok("BE thật: id không tồn tại → màn không tìm thấy", True)
    ok("BE thật: không có lỗi console ngoài 404 cố ý", not [e for e in errs if "404" not in e and "Failed to load resource" not in e and "fonts.g" not in e], str(errs[:3]))
    bad=[x for x in reqs if x[2]>=500]
    ok("BE thật: không có phản hồi 5xx", not bad, str(bad))
    ctx.close()
    # Quản lý
    ctx=b.new_context(viewport={"width":1280,"height":900},reduced_motion="reduce"); page=ctx.new_page()
    page.goto(BASE+"/login/"); page.wait_for_load_state("networkidle")
    page.get_by_label("Tài khoản").fill("ql1"); page.get_by_label("Mật khẩu").fill("Songbien2026"); page.get_by_role("button",name="Đăng nhập").click()
    page.wait_for_selector(".nav a", state="attached")
    page.goto(BASE+"/orders/"); page.wait_for_load_state("networkidle"); expect(page.locator("tbody tr").first).to_be_visible()
    tabs=[t.strip() for t in page.get_by_role("tab").all_inner_texts()]
    ok("BE thật: Quản lý thấy tab Đơn hàng + Phiếu hoàn, không có Hàng chờ", tabs==["Đơn hàng","Phiếu hoàn"], str(tabs))
    page.locator("tbody tr").first.click(); page.wait_for_url(re.compile(r"/orders/detail/\?id=\d+$")); expect(page.locator("main header h2")).to_be_visible(); page.wait_for_load_state("networkidle")
    ok("BE thật: Quản lý không có nút 'Xác nhận đã nhận tiền', không thấy 'Giá vốn'", page.get_by_role("button",name="Xác nhận đã nhận tiền").count()==0 and "Giá vốn" not in page.locator("main").inner_text())
    b.close()
f=[r for r in R if not r[1]]; print(f"{len(R)-len(f)}/{len(R)} PASS"); sys.exit(1 if f else 0)
