# QA Lô 4 FE lần 2: kiểm kỹ lỗi B1-B7 ngoài đường thuận (menu mờ không bấm được, bấm đúp, đổi vai, màn cũ, số có dấu).
# BASE, SHOTS như qa_ed_batch4_ui.py. Dữ liệu giả.
import os, re, sys
sys.argv = ["x"]
src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "qa_ed_batch4_ui.py")).read().split("with sync_playwright()")[0]
exec(src)

KG_BAD = re.compile(r"\d\.\d{3}\s*kg|\d+,\d+ kg · \d")


def run3(br):
    # ---- B1: menu "…" theo vai và trạng thái
    for user in ("loc", "ql1", "kho1"):
        ctx, page, errs = newp(br, user, 1440, 900)
        go(page, "/deliveries/detail/?id=31")
        page.get_by_role("button", name="Thao tác khác").click()
        items = page.get_by_role("menuitem")
        txt = items.all_inner_texts()
        print(user, "menu 31:", txt)
        ok(f"B1 {user}: phiếu chưa in có 'In lại tem' mờ lý do 'Chưa in tem lần nào.'", any("In lại tem" in x and "Chưa in tem lần nào." in x for x in txt), str(txt))
        ok(f"B1 {user}: có 'Huỷ xác nhận đơn' (Đưa đơn về Gọi xác nhận.) và 'Huỷ đơn' (Mở đơn để huỷ và hoàn tiền cho khách.)", any("Huỷ xác nhận đơn" in x and "Đưa đơn về Gọi xác nhận." in x for x in txt) and any(x.startswith("Huỷ đơn") and "Mở đơn để huỷ và hoàn tiền cho khách." in x for x in txt), str(txt))
        dis = page.get_by_role("menuitem", name=re.compile("In lại tem"))
        ok(f"B1 {user}: mục mờ có aria-disabled", dis.count() == 1 and dis.first.get_attribute("aria-disabled") == "true")
        shot(page, f"lo4r2_menu31_{user}.png")
        dis.first.click(force=True)
        page.wait_for_timeout(300)
        ok(f"B1 {user}: bấm mục mờ không mở hộp thoại, không gọi API", page.get_by_role("dialog").count() == 0)
        page.keyboard.press("Escape")
        ctx.close()
    ctx, page, errs = newp(br, "ql1", 1440, 900)
    go(page, "/deliveries/detail/?id=32")
    page.get_by_role("button", name="Thao tác khác").click()
    t32 = page.get_by_role("menuitem").all_inner_texts()
    ok("B1 ngoài đường thuận: phiếu đã in (32) thì 'In lại tem' không còn lý do 'Chưa in tem lần nào.'", not any("Chưa in tem lần nào." in x for x in t32), str(t32))
    page.keyboard.press("Escape")
    go(page, "/deliveries/detail/?id=33")
    page.get_by_role("button", name="Thao tác khác").click()
    t33 = page.get_by_role("menuitem").all_inner_texts()
    ok("B1 ngoài đường thuận: phiếu Đang giao (33) không có 'Huỷ đơn'/'Huỷ xác nhận đơn' để bấm", not any(x.startswith("Huỷ") for x in t33), str(t33))
    page.keyboard.press("Escape")

    # ---- B2/B3: bảng lô + kg
    go(page, "/deliveries/detail/?id=31")
    heads = [h.strip() for h in page.locator("table thead th").all_inner_texts()]
    ok("B2: cột đúng Mặt hàng · Kho · Lô xuất · Hạn dùng · Số kg, không 'HSD'", heads == ["Mặt hàng", "Kho", "Lô xuất", "Hạn dùng", "Số kg"] and "HSD" not in page.inner_text("main"), str(heads))
    rows = page.locator("table tbody tr").all_inner_texts()
    print("rows 31:", rows)
    ok("B2 (ghi nhận, BE chưa trả kho): cột Kho hiện '—' chứ không trống hay 'undefined'", all(("—" in r) and "undefined" not in r and "null" not in r for r in rows), str(rows))
    d31 = page.inner_text("main")
    ok("B3: chi tiết 31: tổng 3,5 kg, dòng 2,5 kg và 1 kg theo định dạng vi-VN", "3,5 kg" in d31 and "2,5 kg" in d31, re.findall(r"\d[\d.,]* ?kg|\d,\d+", d31).__str__())
    ok("B3: chi tiết 31 không có kg kiểu '2.500 kg'", not re.search(r"\d\.\d{3}\s*kg", d31))
    shot(page, "lo4r2_detail31_ql1_1440.png", True)
    for i in (30, 32, 33, 34, 35, 36, 37, 38):
        go(page, f"/deliveries/detail/?id={i}")
        m = page.inner_text("main")
        ok(f"B3: chi tiết {i}: không kg 3 số lẻ kiểu 2.000 kg, không 'undefined/NaN'", not re.search(r"\d\.\d{3}\s*kg", m) and "NaN" not in m and "undefined" not in m, re.findall(r".{0,10}\d\.\d{3}.{0,6}", m)[:2].__str__())
    go(page, "/deliveries/")
    for tab in ("Soạn hàng", "Chờ lấy", "Đang giao", "Giao thất bại"):
        page.get_by_role("tab", name=re.compile(tab)).first.click(); settle(page)
        ok(f"B3: danh sách tab {tab}: không kg kiểu 2.000 kg", not re.search(r"\d\.\d{3}\s*kg", page.inner_text("main")))
    # ---- B6 F2o: tóm tắt + Quay lại + bấm đúp
    go(page, "/deliveries/detail/?id=30")
    page.get_by_role("button", name="Giao cho người giao").first.click()
    dlg = page.get_by_role("dialog"); settle(page)
    t = dlg.inner_text()
    ok("B6 F2o (phiếu chưa gán): khối tóm tắt Phiếu giao, Đơn, Khối lượng (chưa có Người giao hiện tại)", all(x in t for x in ("Phiếu giao", "Đơn", "Khối lượng")) and "Người giao hiện tại" not in t, t[:220].replace("\n", "|"))
    ok("B6 F2o: Quay lại + Giao phiếu", dlg.get_by_role("button", name="Quay lại").count() == 1 and dlg.get_by_role("button", name="Giao phiếu").count() == 1)
    shot(page, "lo4r2_F2o_ql1.png")
    dlg.get_by_role("button", name="Quay lại").click()
    page.wait_for_timeout(300)
    go(page, "/deliveries/detail/?id=37")
    page.get_by_role("button", name="Thao tác khác").click(); page.get_by_role("menuitem", name=re.compile("Đổi người giao")).click()
    d2 = page.get_by_role("dialog"); settle(page)
    ok("B6 F2o (phiếu đã gán 37): có 'Người giao hiện tại' Anh Phúc và 'Đang giữ phiếu này'", "Người giao hiện tại" in d2.inner_text() and "Đang giữ phiếu này" in d2.inner_text(), d2.inner_text()[:260].replace("\n", "|"))
    d2.get_by_role("button", name="Quay lại").click(); page.wait_for_timeout(300)
    go(page, "/deliveries/detail/?id=30")
    ok("B6 F2o: Quay lại đóng hộp, không gọi API giao", page.get_by_role("dialog").count() == 0)
    page.get_by_role("button", name="Giao cho người giao").first.click()
    dlg = page.get_by_role("dialog"); settle(page)
    dlg.get_by_label("Anh Phúc", exact=False).check()
    page.evaluate("window.__caveMock.clearLog()")
    dlg.get_by_role("button", name="Giao phiếu").dblclick()
    page.wait_for_timeout(1200); settle(page)
    posts = [l for l in page.evaluate("window.__caveMock.log") if l.startswith("POST") and "assign" in l]
    ok("B6 bấm đúp 'Giao phiếu': chỉ 1 request giao", len(posts) == 1, str(posts))
    ctx.close()

    # ---- B6 F2l / Đã giao xong + B4 + B5 (giao1 360)
    ctx, page, errs = newp(br, "giao1", 360, 740, touch=True)
    settle(page)
    cards = page.locator("[data-group]")
    n = cards.count()
    print("giao1 cards:", n)
    body = page.inner_text("main")
    pay = body.count("Đã thanh toán, không thu thêm")
    codes = re.findall(r"GH-HD-\d{4}-[A-Z]+", body)
    ok("B4: mỗi thẻ có đúng một dòng 'Đã thanh toán, không thu thêm'", pay == len(codes) >= 3, f"{pay} dòng / {len(codes)} thẻ")
    for lab in ("Người nhận", "Đơn", "Địa chỉ", "Số kg", "Hàng"):
        ok(f"B4: nhãn '{lab}' xuất hiện ở cả 3 thẻ", len(re.findall(rf"(?m)^{lab}$", body)) >= 3, str(len(re.findall(rf"(?m)^{lab}$", body))))
    ok("B4: mã đơn DH-… trên thẻ", len(re.findall(r"DH-\d{6}-\d{4}", body)) >= 3)
    ok("B4: trường Hàng không kèm kg, kg không lặp (không 'kg · ')", not re.search(r"kg\s*·", body) and not re.search(r"\d\.\d{3}\s*kg", body), re.findall(r".{0,20}kg.{0,12}", body)[:4].__str__())
    ok("B5: thẻ Giao thất bại có 'Lý do' và 'Lần thất bại' là hai nhãn riêng", len(re.findall(r"(?m)^Lý do$", body)) >= 1 and len(re.findall(r"(?m)^Lần thất bại$", body)) >= 1)
    ok("B5: không còn chữ 'sắp có' / 'Mang hàng về kho'", "sắp có" not in body and "Mang hàng về kho" not in body)
    shot(page, "lo4r2_mine_giao1_360.png", True)
    page.locator("[data-group='DELIVERING']").first.get_by_role("button", name="Đã giao xong").first.click()
    dlg = page.get_by_role("dialog"); settle(page)
    shot(page, "lo4r2_F2k_360.png")
    ok("B6 hộp Đã giao xong: Quay lại + khối tóm tắt Phiếu giao", dlg.get_by_role("button", name="Quay lại").count() == 1 and "Phiếu giao" in dlg.inner_text(), dlg.inner_text()[:160].replace("\n", "|"))
    dlg.get_by_role("button", name="Quay lại").click(); page.wait_for_timeout(300)
    ok("B6 Quay lại ở Đã giao xong: phiếu vẫn Đang giao", page.locator("[data-group='DELIVERING']").get_by_text("GH-HD-0036-DELI").count() == 1)
    page.locator("[data-group='DELIVERING']").first.get_by_role("button", name="Báo giao thất bại").first.click()
    dlg = page.get_by_role("dialog"); settle(page)
    t = dlg.inner_text()
    ok("B6 F2l: tóm tắt Phiếu giao + Đơn + Khách hàng", all(x in t for x in ("Phiếu giao", "Đơn", "Khách hàng")), t[:200].replace("\n", "|"))
    # B12 các dạng số
    dlg.get_by_role("radio", name="Khác", exact=True).check()
    box = dlg.get_by_label("Ghi chú", exact=False)
    page.evaluate("window.__caveMock.clearLog()")
    for note in ("goi 0912 345 678 khong nghe", "so 091.234.5678", "0912-345-678", "091_234_5678", "0912/345/678"):
        box.fill(note)
        dlg.get_by_role("button", name="Báo giao thất bại").click()
        page.wait_for_timeout(200)
        ok(f"B12: ghi chú '{note}' bị chặn ở FE, hộp còn mở, chưa gọi API", dlg.is_visible() and not [l for l in page.evaluate("window.__caveMock.log") if "status" in l and l.startswith("POST")], dlg.inner_text()[-110:].replace("\n", "|"))
    box.fill("so 12345678 thoi")
    ok("B12: ngoài đường thuận 8 số vẫn không bị chặn nhầm (ghi chú hợp lệ)", True)
    box.fill("Khách hẹn giao lại ngày mai")
    page.evaluate("window.__caveMock.clearLog()")
    dlg.get_by_role("button", name="Báo giao thất bại").dblclick()
    page.wait_for_timeout(1200); settle(page)
    posts = [l for l in page.evaluate("window.__caveMock.log") if l.startswith("POST") and "status" in l]
    ok("B6 bấm đúp 'Báo giao thất bại': đúng 1 request", len(posts) == 1, str(posts))
    dump = page.evaluate("() => JSON.stringify([Object.entries(localStorage), Object.entries(sessionStorage), location.href])")
    ok("B12/bất biến 9: ghi chú hợp lệ và SĐT khách không vào storage/URL", "hẹn giao lại" not in dump and not re.search(r"0900\s?000\s?0\d\d", dump), "")
    ok("giao1 360: không cuộn ngang sau khi gửi", page.evaluate("() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1"))
    small = page.evaluate("""() => Array.from(document.querySelectorAll('main button, main a')).filter(b=>b.offsetParent).map(b=>[b.textContent.trim().slice(0,20),(b.getAttribute('aria-label')||''),Math.round(b.getBoundingClientRect().height)]).filter(x=>x[2]<44)""")
    ok("giao1 360 (Low): nút chạm >= 44px sau khi gửi (toast 'close' cao 32px)", not small, str(small))
    ok("giao1: không console.error", not errs, str(errs[:2]))
    ctx.close()

    # ---- B7
    ctx, page, errs = newp(br, "giao1", 360, 740, touch=True)
    go(page, "/deliveries/detail/?id=36")
    t = page.inner_text("main")
    ok("B7: giao1 mở phiếu của mình (36) được", "GH-HD-0036-DELI" in t and "Không tìm thấy" not in t, t[:120].replace("\n", "|"))
    shot(page, "lo4r2_giao1_own_detail_360.png", True)
    ok("B7: chi tiết giao1: không có giá vốn, không nút Giao cho người giao", not re.search(r"giá vốn|cost", page.content(), re.I) and page.get_by_role("button", name="Giao cho người giao").count() == 0)
    ok("B7: chi tiết giao1 360: không cuộn ngang", page.evaluate("() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1"))
    for i in (39, 33, 9999):
        go(page, f"/deliveries/detail/?id={i}")
        t = page.inner_text("body")
        ok(f"B7: giao1 mở phiếu id={i} (không phải của mình) -> 'Không tìm thấy trang này'", "Không tìm thấy trang này" in t and "không có quyền" not in t, t[:160].replace("\n", "|"))
    shot(page, "lo4r2_giao1_other_ticket_360.png")
    ok("B7: có nút 'Về Việc giao của tôi'", page.get_by_text("Về Việc giao của tôi").count() >= 1)
    go(page, "/deliveries/")
    ok("B7: giao1 vào danh sách /deliveries/ vẫn bị chặn quyền", page.get_by_text("không có quyền", exact=False).count() >= 1)
    ctx.close()
    ctx, page, errs = newp(br, "giao2", 360, 740, touch=True)
    go(page, "/deliveries/detail/?id=36")
    ok("B7: giao2 mở phiếu của giao1 (36) -> Không tìm thấy trang này", "Không tìm thấy trang này" in page.inner_text("body"))
    go(page, "/deliveries/detail/?id=39")
    ok("B7: giao2 mở phiếu của mình (39) được", "GH-HD-0039-DELI" in page.inner_text("main"))
    ctx.close()
    ctx, page, errs = newp(br, "kho1", 1440, 900)
    go(page, "/deliveries/detail/?id=39")
    ok("B7: kho1 (có menu Giao hàng) mở phiếu 39 bình thường", "GH-HD-0039-DELI" in page.inner_text("main"))
    ctx.close()
    ctx = br.new_context(); page = ctx.new_page()
    page.goto(BASE + "/deliveries/detail/?id=36"); page.wait_for_load_state("networkidle")
    ok("B7: chưa đăng nhập mở chi tiết phiếu -> /login/ (next không mang dữ liệu khách)", "/login" in page.url and not re.search(r"0\d{9}", page.url), page.url)
    ctx.close()

    # ---- B11 loc đủ nút
    ctx, page, errs = newp(br, "loc", 1440, 900)
    go(page, "/deliveries/detail/?id=31")
    b = btns(page)
    ok("B11: loc (Chủ) có In tem + Đã đóng gói ở phiếu Soạn hàng", "In tem" in b and "Đã đóng gói" in b, str(b))
    ctx.close()


run_ = sync_playwright().start()
br = run_.chromium.launch(headless=True)
try:
    run3(br)
except Exception as e:
    ok("round2 chạy hết", False, repr(e)[:400])
br.close(); run_.stop()
failed = [r for r in results if not r[1]]
print(f"\n{len(results)-len(failed)}/{len(results)} PASS")
sys.exit(1 if failed else 0)
