# Generated by Django 5.1.15 on 2026-09-29 07:08

import apps.catalog.models.images
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('name_key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('slug', models.CharField(db_index=True, max_length=80, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'default_permissions': ('view', 'add', 'change'),
            },
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(default=apps.catalog.models.images.generate_image_id, editable=False, max_length=32, unique=True)),
                ('alt', models.CharField(blank=True, default='', max_length=200)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_content_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post', 'Bài viết'), ('page', 'Trang')], default='post', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('pending_review', 'Chờ duyệt'), ('published', 'Đã đăng'), ('unpublished', 'Đã gỡ')], db_index=True, default='draft', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=120, unique=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.JSONField(default=dict)),
                ('draft_hash', models.CharField(blank=True, default='', max_length=64)),
                ('first_published_at', models.DateTimeField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('restored_from', models.PositiveIntegerField(blank=True, null=True)),
                ('return_reason', models.CharField(blank=True, default='', max_length=20)),
                ('page_role', models.CharField(blank=True, choices=[('privacy', 'Bảo mật'), ('terms', 'Điều kiện giao dịch'), ('refund', 'Đổi trả hoàn tiền'), ('seller_info', 'Thông tin người bán')], max_length=16, null=True)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('footer_order', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(choices=[('human', 'Người dùng'), ('ai', 'AI')], default='human', max_length=8)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='content.category')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.contentimage')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_content_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('publish_entry', 'Đăng, gỡ, trả về nháp bài; đặt trang go-live và footer')],
            },
        ),
        migrations.AddField(
            model_name='contentimage',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.entry'),
        ),
        migrations.CreateModel(
            name='EntryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=8)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.CharField(max_length=120)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.JSONField(default=dict)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('restored_from', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.category')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.contentimage')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='content.entry')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_entry_versions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.entryversion'),
        ),
        migrations.AddConstraint(
            model_name='entryversion',
            constraint=models.UniqueConstraint(fields=('entry', 'version'), name='unique_entry_version'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['kind', 'status', 'first_published_at'], name='idx_content_entry_pub'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('page_role__isnull', False)), fields=('page_role',), name='unique_entry_page_role'),
        ),
    ]
