# Generated by Django 5.1.15 on 2026-10-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_grant_content_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='page_role',
            field=models.CharField(blank=True, choices=[('privacy', 'Chính sách bảo mật'), ('terms', 'Điều kiện giao dịch chung'), ('refund', 'Chính sách đổi trả và hoàn tiền'), ('seller_info', 'Thông tin người bán')], max_length=16, null=True),
        ),
    ]
