# Generated by Django 5.1.15 on 2026-10-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_entry_page_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='page_role',
            field=models.CharField(blank=True, choices=[('privacy', 'Chính sách bảo mật'), ('terms', 'Điều kiện giao dịch chung'), ('refund', 'Chính sách đổi trả và hoàn tiền'), ('seller_info', 'Thông tin người bán'), ('shipping', 'Chính sách giao hàng'), ('payment', 'Chính sách thanh toán'), ('complaints', 'Cơ chế giải quyết khiếu nại')], max_length=16, null=True),
        ),
    ]
