# Generated by Django 5.1.15 on 2026-09-28 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='Phiên bản')),
                ('global_mode', models.CharField(choices=[('on', 'Bật'), ('c_only', 'Chỉ mức C'), ('off', 'Tắt')], default='on', max_length=10, verbose_name='Chế độ toàn cục')),
                ('red_zone_open', models.JSONField(blank=True, default=dict, verbose_name='Trạng thái mở vùng đỏ')),
                ('caps', models.JSONField(blank=True, default=dict, verbose_name='Trần của Chủ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo phiên bản')),
            ],
            options={
                'verbose_name': 'Phiên bản chính sách AI',
                'verbose_name_plural': 'Phiên bản chính sách AI',
                'ordering': ['-version'],
                'permissions': [('manage_ai_policy', 'Quản lý chính sách AI')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AiAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command', models.CharField(max_length=128, verbose_name='Mã lệnh')),
                ('kind', models.CharField(choices=[('read', 'Đọc'), ('write', 'Ghi')], max_length=10, verbose_name='Loại lệnh')),
                ('level', models.CharField(choices=[('A', 'Mức A'), ('B', 'Mức B'), ('C', 'Mức C')], max_length=1, verbose_name='Mức tự chủ')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('CONFIRMED', 'Đã duyệt'), ('REJECTED', 'Đã từ chối'), ('EXPIRED', 'Hết hạn'), ('SCHEDULED', 'Đã lên lịch'), ('DONE', 'Đã thực hiện'), ('UNDONE', 'Đã hoàn tác'), ('CANCELLED', 'Đã huỷ'), ('ESCALATED', 'Đã chuyển việc'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('config_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Phiên bản cấu hình lúc tạo')),
                ('policy_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Phiên bản chính sách lúc tạo')),
                ('target_model', models.CharField(blank=True, max_length=100, verbose_name='Model đích')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='ID đích')),
                ('args', models.JSONField(blank=True, default=dict, verbose_name='Tham số đầu vào')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, verbose_name='Khóa chống trùng')),
                ('channel', models.CharField(default='ai_local', max_length=32, verbose_name='Kênh')),
                ('client', models.CharField(default='erp-console', max_length=64, verbose_name='Ứng dụng client')),
                ('downgrade_reason', models.JSONField(blank=True, null=True, verbose_name='Lý do hạ mức')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hạn duyệt')),
                ('execute_after', models.DateTimeField(blank=True, null=True, verbose_name='Lên lịch chạy sau')),
                ('undo_until', models.DateTimeField(blank=True, null=True, verbose_name='Hạn hoàn tác')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm mở xem')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm quyết định')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm thực thi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('assignee_group', models.CharField(blank=True, max_length=50, verbose_name='Nhóm nhận việc')),
                ('result_ref', models.JSONField(blank=True, null=True, verbose_name='Tham chiếu kết quả')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người quyết định')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_actions', to=settings.AUTH_USER_MODEL, verbose_name='Chủ AI')),
            ],
            options={
                'verbose_name': 'Hành động AI',
                'verbose_name_plural': 'Hành động AI',
                'ordering': ['-created_at'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['owner', 'status', '-created_at'], name='ai_action_owner_status_idx'), models.Index(fields=['status', 'execute_after'], name='ai_action_status_exec_idx'), models.Index(fields=['created_at'], name='ai_action_created_at_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('owner', 'idempotency_key'), name='uniq_owner_ai_action_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='AiConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Phiên bản')),
                ('group_levels', models.JSONField(blank=True, default=dict, verbose_name='Mặc định nhóm')),
                ('overrides', models.JSONField(blank=True, default=dict, verbose_name='Chỉnh riêng theo lệnh')),
                ('limits', models.JSONField(blank=True, default=dict, verbose_name='Ngưỡng theo lệnh')),
                ('killed', models.BooleanField(default=False, verbose_name='Tắt khẩn theo user')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo phiên bản')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_config_versions', to=settings.AUTH_USER_MODEL, verbose_name='Chủ AI')),
            ],
            options={
                'verbose_name': 'Phiên bản cấu hình AI',
                'verbose_name_plural': 'Phiên bản cấu hình AI',
                'ordering': ['-version'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['user', '-version'], name='ai_config_user_ver_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'version'), name='uniq_user_ai_config_version')],
            },
        ),
    ]
