# Generated by Django 5.1.15 on 2026-09-13 15:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên bảng giá')),
                ('currency', models.CharField(default='VND', max_length=8, verbose_name='Tiền tệ')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mặc định')),
            ],
            options={
                'verbose_name': 'Bảng giá',
                'verbose_name_plural': 'Bảng giá',
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên nhóm')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.itemgroup', verbose_name='Nhóm cha')),
            ],
            options={
                'verbose_name': 'Nhóm hàng',
                'verbose_name_plural': 'Nhóm hàng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã hàng')),
                ('name', models.CharField(max_length=200, verbose_name='Tên hàng')),
                ('item_type', models.CharField(choices=[('SIMPLE', 'Mặt hàng thường'), ('BUNDLE', 'Combo dạng gói (có công thức)')], default='SIMPLE', max_length=10, verbose_name='Loại')),
                ('stock_uom', models.CharField(default='Kg', max_length=10, verbose_name='Đơn vị')),
                ('shelf_life_in_days', models.PositiveIntegerField(default=90, verbose_name='Hạn dùng mặc định (ngày)')),
                ('has_batch_no', models.BooleanField(default=True, verbose_name='Quản lý theo lô')),
                ('has_expiry_date', models.BooleanField(default=True, verbose_name='Có hạn dùng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.itemgroup', verbose_name='Nhóm hàng')),
            ],
            options={
                'verbose_name': 'Mặt hàng',
                'verbose_name_plural': 'Mặt hàng',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá (đ/kg)')),
                ('valid_from', models.DateField(verbose_name='Hiệu lực từ')),
                ('valid_upto', models.DateField(blank=True, null=True, verbose_name='Hiệu lực đến')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.item', verbose_name='Mặt hàng')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.pricelist', verbose_name='Bảng giá')),
            ],
            options={
                'verbose_name': 'Giá niêm yết',
                'verbose_name_plural': 'Giá niêm yết',
                'ordering': ['item', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên ưu đãi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('apply_on', models.CharField(choices=[('ITEM', 'Theo mặt hàng (mua ≥ N kg)'), ('ORDER', 'Theo đơn (tổng ≥ M đồng)')], max_length=8, verbose_name='Áp dụng trên')),
                ('min_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Số kg tối thiểu')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá trị đơn tối thiểu (đ)')),
                ('discount_type', models.CharField(choices=[('AMOUNT', 'Giảm số tiền'), ('PERCENT', 'Giảm phần trăm')], max_length=8, verbose_name='Kiểu giảm')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Mức giảm')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Hiệu lực từ')),
                ('valid_upto', models.DateField(blank=True, null=True, verbose_name='Hiệu lực đến')),
                ('item', models.ForeignKey(blank=True, help_text="Bắt buộc khi 'Áp dụng trên' = Theo mặt hàng.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_rules', to='catalog.item', verbose_name='Mặt hàng điều kiện')),
            ],
            options={
                'verbose_name': 'Ưu đãi',
                'verbose_name_plural': 'Ưu đãi',
            },
        ),
        migrations.CreateModel(
            name='BundleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_bundle', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Định mức (kg / 1 combo)')),
                ('bundle', models.ForeignKey(limit_choices_to={'item_type': 'BUNDLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_lines', to='catalog.item', verbose_name='Combo')),
                ('component', models.ForeignKey(limit_choices_to={'item_type': 'SIMPLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='catalog.item', verbose_name='Thành phần')),
            ],
            options={
                'verbose_name': 'Thành phần combo',
                'verbose_name_plural': 'Thành phần combo',
                'constraints': [models.UniqueConstraint(fields=('bundle', 'component'), name='uniq_bundle_component')],
            },
        ),
    ]
