# Generated by Django 5.1.15 on 2026-09-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shelf_life_in_days',
            field=models.PositiveIntegerField(default=365, verbose_name='Hạn dùng mặc định (ngày)'),
        ),
    ]
