# Generated by Django 5.1.15 on 2026-09-26 18:20

import apps.catalog.models.images
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_shelf_life_in_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['code'], 'permissions': [('change_item_image', 'Thêm / thay / gỡ ảnh mặt hàng')], 'verbose_name': 'Mặt hàng', 'verbose_name_plural': 'Mặt hàng'},
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(default=apps.catalog.models.images.generate_image_id, editable=False, max_length=32, unique=True, verbose_name='Mã ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=125, verbose_name='Alt text')),
                ('is_illustration', models.BooleanField(default=False, verbose_name='Ảnh minh hoạ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tải lên lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.item', verbose_name='Mặt hàng')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Ảnh mặt hàng',
                'verbose_name_plural': 'Ảnh mặt hàng',
            },
        ),
    ]
