# Generated by Django 5.1.15 on 2026-10-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_item_options_itemimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['code'], 'permissions': [('change_item_image', 'Sửa ảnh mặt hàng')], 'verbose_name': 'Mặt hàng', 'verbose_name_plural': 'Mặt hàng'},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('SIMPLE', 'Mặt hàng thường'), ('BUNDLE', 'Combo')], default='SIMPLE', max_length=10, verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='apply_on',
            field=models.CharField(choices=[('ITEM', 'Theo mặt hàng'), ('ORDER', 'Theo đơn')], max_length=8, verbose_name='Áp dụng trên'),
        ),
    ]
