# Generated by Django 5.1.15 on 2026-10-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_itemgroup_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nguồn hàng'),
        ),
        migrations.AddField(
            model_name='item',
            name='short_note',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Ghi chú ngắn'),
        ),
        migrations.AddField(
            model_name='item',
            name='spec',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Quy cách'),
        ),
        migrations.AddField(
            model_name='item',
            name='storage',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Bảo quản'),
        ),
    ]
