# Generated by Django 5.1.15 on 2026-09-13 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Mã phiếu giao')),
                ('status', models.CharField(choices=[('PREPARING', 'Soạn hàng'), ('READY', 'Chờ lấy hàng'), ('DELIVERING', 'Đang giao'), ('COMPLETED', 'Hoàn tất'), ('FAILED', 'Giao thất bại')], default='PREPARING', max_length=12, verbose_name='Trạng thái')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Số lần giao thất bại')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn tất')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên giao')),
            ],
            options={
                'verbose_name': 'Phiếu giao hàng',
                'verbose_name_plural': 'Phiếu giao hàng',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
