# Generated by Django 5.1.15 on 2026-09-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Soạn hàng'), ('READY', 'Chờ lấy hàng'), ('DELIVERING', 'Đang giao'), ('COMPLETED', 'Hoàn tất'), ('FAILED', 'Giao thất bại'), ('CANCELLED', 'Đã huỷ theo đơn')], default='PREPARING', max_length=12, verbose_name='Trạng thái'),
        ),
    ]
