# Generated by Django 5.1.15 on 2026-09-28 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliverynote_status'),
        ('sales', '0006_salesorder_checkout_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverynote',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('confirm_with_customer', 'Gọi xác nhận đơn'), ('change_recipient', 'Đổi thông tin nhận hàng'), ('decide_unconfirmed', 'Quyết định đơn không liên lạc được'), ('pack_deliverynote', 'Đóng gói phiếu giao'), ('print_label', 'In / huỷ tem giao')], 'verbose_name': 'Phiếu giao hàng', 'verbose_name_plural': 'Phiếu giao hàng'},
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='confirm_skipped',
            field=models.BooleanField(default=False, verbose_name='Bỏ qua xác nhận'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xác nhận'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Tên người nhận'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='SĐT người nhận'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('CONFIRMING', 'Chờ xác nhận'), ('PREPARING', 'Soạn hàng'), ('READY', 'Chờ lấy hàng'), ('DELIVERING', 'Đang giao'), ('COMPLETED', 'Hoàn tất'), ('FAILED', 'Giao thất bại'), ('CANCELLED', 'Đã huỷ theo đơn')], default='PREPARING', max_length=12, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='ConfirmationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'Chờ gọi'), ('CALLBACK', 'Hẹn gọi lại'), ('ESCALATED', 'Cần quyết định'), ('REFUND_CALL', 'Gọi báo hoàn tiền'), ('DONE', 'Hoàn tất')], db_index=True, default='PENDING', max_length=12, verbose_name='Tình trạng gọi')),
                ('escalation_reason', models.CharField(blank=True, choices=[('UNREACHABLE', 'Không nghe máy'), ('WRONG_NUMBER', 'Sai số'), ('WANT_CANCEL', 'Khách muốn huỷ'), ('WANT_CHANGE', 'Khách muốn đổi')], default='', max_length=16, verbose_name='Lý do cần quyết định')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Số lần gọi không được')),
                ('first_unreachable_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần đầu không liên lạc được')),
                ('last_unreachable_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần gần nhất không liên lạc được')),
                ('callback_at', models.DateTimeField(blank=True, null=True, verbose_name='Hẹn gọi lại lúc')),
                ('escalated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Chuyển Quản lý lúc')),
                ('auto_cancel_blocked_code', models.CharField(blank=True, default='', max_length=16, verbose_name='Mã chặn tự huỷ')),
                ('auto_cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm Hệ thống tự huỷ')),
                ('claimed_until', models.DateTimeField(blank=True, null=True, verbose_name='Hạn giữ xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người đang xử lý')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='delivery.deliverynote', verbose_name='Phiếu giao')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.refund', verbose_name='Phiếu hoàn tiền liên quan')),
            ],
            options={
                'verbose_name': 'Mục chờ gọi CSKH',
                'verbose_name_plural': 'Mục chờ gọi CSKH',
                'default_permissions': (),
                'indexes': [models.Index(fields=['state', 'escalated_at'], name='delivery_co_state_c7a41d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('CONFIRMED', 'Đã xác nhận'), ('CONFIRMED_CHANGED', 'Xác nhận có đổi thông tin'), ('UNREACHABLE', 'Không nghe máy'), ('WRONG_NUMBER', 'Sai số'), ('CALLBACK', 'Hẹn gọi lại'), ('WANT_CHANGE', 'Khách muốn đổi món/số lượng'), ('WANT_CANCEL', 'Khách muốn huỷ'), ('NOTIFIED', 'Đã báo hoàn tiền')], max_length=20, verbose_name='Kết quả gọi')),
                ('note_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Ghi chú cuộc gọi')),
                ('callback_at', models.DateTimeField(blank=True, null=True, verbose_name='Hẹn gọi lại lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Mã chống trùng')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người gọi')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='delivery.deliverynote', verbose_name='Phiếu giao')),
            ],
            options={
                'verbose_name': 'Bản ghi cuộc gọi',
                'verbose_name_plural': 'Bản ghi cuộc gọi',
                'ordering': ['-created_at', '-id'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['created_by', 'created_at'], name='delivery_cu_created_83e473_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabelPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_no', models.PositiveSmallIntegerField(verbose_name='Số thứ tự in')),
                ('reason', models.CharField(choices=[('FIRST', 'In lần đầu'), ('REPRINT', 'In lại'), ('ADDRESS_CHANGED', 'Đổi thông tin nhận')], default='FIRST', max_length=16, verbose_name='Lý do in')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Mã chống trùng')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm bị thay thế')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm huỷ tem')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_prints', to='delivery.deliverynote', verbose_name='Phiếu giao')),
                ('printed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người in')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người huỷ tem')),
            ],
            options={
                'verbose_name': 'Lượt in tem giao',
                'verbose_name_plural': 'Lượt in tem giao',
                'ordering': ['print_no'],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('note', 'print_no'), name='uniq_delivery_label_print')],
            },
        ),
    ]
