# Generated by Django 5.1.15 on 2026-10-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_cskh_confirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverynote',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('confirm_with_customer', 'Gọi xác nhận đơn'), ('change_recipient', 'Đổi thông tin nhận hàng'), ('decide_unconfirmed', 'Quyết định đơn không liên lạc được'), ('pack_deliverynote', 'Đóng gói phiếu giao'), ('print_label', 'In / huỷ tem giao'), ('assign_deliverynote', 'Giao phiếu cho người giao')], 'verbose_name': 'Phiếu giao hàng', 'verbose_name_plural': 'Phiếu giao hàng'},
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='failure_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ghi chú giao thất bại'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('NOT_MET', 'Không gặp khách'), ('REFUSED', 'Khách từ chối nhận'), ('WRONG_ADDRESS', 'Sai địa chỉ'), ('DAMAGED', 'Hàng hư khi giao'), ('OTHER', 'Khác')], default='', max_length=16, verbose_name='Lý do giao thất bại'),
        ),
    ]
