# Generated by Django 5.1.15 on 2026-10-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_grant_assign_deliverynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu giao lúc'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giao thất bại lúc'),
        ),
    ]
