# Generated by Django 5.1.15 on 2026-10-06 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliverynote_delivery_started_failed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(choices=[('FIRST_ORDER', 'Khách mua lần đầu'), ('RETURNING', 'Khách quen'), ('COMBO', 'Đơn có combo'), ('GENERAL', 'Lời dặn chung')], max_length=16, unique=True, verbose_name='Tình huống')),
                ('content', models.TextField(max_length=2000, verbose_name='Nội dung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa cuối')),
            ],
            options={
                'verbose_name': 'Kịch bản gọi',
                'verbose_name_plural': 'Kịch bản gọi',
                'ordering': ['situation'],
                'default_permissions': ('view', 'add', 'change'),
            },
        ),
    ]
