# Generated by Django 5.1.15 on 2026-10-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_grant_callscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationtask',
            name='decision_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lý do quyết định'),
        ),
    ]
