# Generated by Django 5.1.15 on 2026-10-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_confirmationtask_decision_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmationtask',
            options={'default_permissions': (), 'verbose_name': 'Việc gọi xác nhận', 'verbose_name_plural': 'Việc gọi xác nhận'},
        ),
        migrations.AlterModelOptions(
            name='deliverynote',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('confirm_with_customer', 'Gọi xác nhận đơn'), ('change_recipient', 'Đổi thông tin nhận hàng'), ('decide_unconfirmed', 'Quyết định đơn không liên lạc được'), ('pack_deliverynote', 'Soạn hàng'), ('print_label', 'In / huỷ tem giao'), ('assign_deliverynote', 'Chọn người giao')], 'verbose_name': 'Phiếu giao', 'verbose_name_plural': 'Phiếu giao'},
        ),
        migrations.AlterField(
            model_name='confirmationtask',
            name='escalation_reason',
            field=models.CharField(blank=True, choices=[('UNREACHABLE', 'Không nghe máy'), ('WRONG_NUMBER', 'Sai số điện thoại'), ('WANT_CANCEL', 'Khách muốn huỷ đơn'), ('WANT_CHANGE', 'Khách muốn đổi món')], default='', max_length=16, verbose_name='Lý do cần quyết định'),
        ),
        migrations.AlterField(
            model_name='confirmationtask',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Chờ gọi'), ('CALLBACK', 'Hẹn gọi lại'), ('ESCALATED', 'Cần quyết định'), ('REFUND_CALL', 'Gọi báo hoàn tiền'), ('DONE', 'Đã xong')], db_index=True, default='PENDING', max_length=12, verbose_name='Tình trạng gọi'),
        ),
        migrations.AlterField(
            model_name='customercall',
            name='result',
            field=models.CharField(choices=[('CONFIRMED', 'Đã xác nhận'), ('CONFIRMED_CHANGED', 'Đã xác nhận, có đổi thông tin'), ('UNREACHABLE', 'Không nghe máy'), ('WRONG_NUMBER', 'Sai số điện thoại'), ('CALLBACK', 'Hẹn gọi lại'), ('WANT_CHANGE', 'Khách muốn đổi món'), ('WANT_CANCEL', 'Khách muốn huỷ đơn'), ('NOTIFIED', 'Đã báo hoàn tiền')], max_length=20, verbose_name='Kết quả gọi'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('CONFIRMING', 'Chờ gọi xác nhận'), ('PREPARING', 'Đang soạn hàng'), ('READY', 'Chờ lấy hàng'), ('DELIVERING', 'Đang giao'), ('COMPLETED', 'Đã giao'), ('FAILED', 'Giao thất bại'), ('CANCELLED', 'Đã huỷ theo đơn')], default='PREPARING', max_length=12, verbose_name='Trạng thái'),
        ),
    ]
