# Generated by Django 5.1.15 on 2026-09-13 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Hành động')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Loại chứng từ')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='Mã đối tượng')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Mô tả đối tượng')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Giá trị trước → sau')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký hành động',
                'verbose_name_plural': 'Nhật ký hành động',
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='Tên hiển thị')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='Ngày vào làm')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang làm'), ('INACTIVE', 'Nghỉ')], default='ACTIVE', max_length=10, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ nhân viên',
                'verbose_name_plural': 'Hồ sơ nhân viên',
                'permissions': [('manage_staff', 'Quản lý nhân viên (tạo tài khoản, đổi Group)')],
            },
        ),
    ]
