# Generated by Django 5.1.15 on 2026-09-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_grant_view_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Phải đổi mật khẩu'),
        ),
    ]
