# Generated by Django 5.1.15 on 2026-09-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile_must_change_password'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64, verbose_name='Mã bản ghi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Loại bản ghi')),
            ],
            options={
                'verbose_name': 'Bản ghi demo',
                'verbose_name_plural': 'Bản ghi demo',
                'default_permissions': ('view',),
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='uniq_demo_record')],
            },
        ),
    ]
