# Generated by Django 5.1.15 on 2026-09-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_grant_cancel_expired_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ai_config_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Phiên bản cấu hình AI'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ai_level',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Mức tự chủ AI'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ai_policy_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Phiên bản chính sách AI'),
        ),
    ]
