# Generated by Django 5.1.15 on 2026-10-06 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_groups_to_english'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_config', to='auth.group')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GroupDataScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_scopes', to='auth.group')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('group', 'object_key'), name='uniq_group_data_scope')],
            },
        ),
    ]
