# Generated by Django 5.1.15 on 2026-10-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_seed_group_data_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='actor_kind',
            field=models.CharField(choices=[('user', 'Người'), ('system', 'Hệ thống'), ('ai', 'AI (thay người dùng)')], default='user', max_length=10, verbose_name='Loại tác nhân'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang làm'), ('INACTIVE', 'Đã nghỉ')], default='ACTIVE', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
