# Generated by Django 5.1.15 on 2026-09-13 15:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('supplier_type', models.CharField(choices=[('INDIVIDUAL', 'Cá nhân'), ('COMPANY', 'Doanh nghiệp')], default='INDIVIDUAL', max_length=12, verbose_name='Loại')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hợp tác')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('ICE', 'Đá'), ('TRANSPORT', 'Vận chuyển'), ('LOADING', 'Bốc vác'), ('OTHER', 'Khác')], max_length=12, verbose_name='Loại chi phí')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Số tiền')),
                ('allocation_method', models.CharField(choices=[('BY_QTY', 'Theo số kg'), ('BY_VALUE', 'Theo giá trị')], default='BY_QTY', max_length=10, verbose_name='Phân bổ theo')),
                ('incurred_date', models.DateField(verbose_name='Ngày phát sinh')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_costs', to=settings.AUTH_USER_MODEL, verbose_name='Người ghi')),
            ],
            options={
                'verbose_name': 'Chi phí mua hàng',
                'verbose_name_plural': 'Chi phí mua hàng',
                'ordering': ['-incurred_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(verbose_name='Ngày nhập')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã ghi nhận')], default='DRAFT', max_length=10, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.warehouse', verbose_name='Kho nhập')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Số lượng (kg)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá mua (đ/kg)')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, help_text='Bỏ trống = lấy theo Item. Cho sửa thấp hơn, không cao hơn (BR-MH-02).', null=True, verbose_name='Hạn dùng (ngày)')),
                ('batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_line', to='inventory.batch', verbose_name='Lô sinh ra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item', verbose_name='Mặt hàng')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchasereceipt', verbose_name='Phiếu nhập')),
            ],
            options={
                'verbose_name': 'Dòng nhập kho',
                'verbose_name_plural': 'Dòng nhập kho',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Số tiền')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Đã trả tiền')),
                ('invoice_date', models.DateField(verbose_name='Ngày hoá đơn')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm trả')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Người ghi')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchasing.purchasereceipt', verbose_name='Phiếu nhập liên quan')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchasing.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Hoá đơn mua',
                'verbose_name_plural': 'Hoá đơn mua',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tiền phân bổ')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='inventory.batch', verbose_name='Lô nhận')),
                ('purchase_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchasing.purchasecost', verbose_name='Chi phí')),
            ],
            options={
                'verbose_name': 'Phân bổ chi phí',
                'verbose_name_plural': 'Phân bổ chi phí',
                'constraints': [models.UniqueConstraint(fields=('purchase_cost', 'batch'), name='uniq_cost_batch')],
            },
        ),
    ]
