# Generated by Django 5.1.15 on 2026-09-28 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_batch_options'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Khoá lặp (idempotency)'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('created_by', 'idempotency_key'), name='uniq_purchase_receipt_idempotency'),
        ),
    ]
