# Generated by Django 5.1.15 on 2026-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchasereceipt_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereceipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã ghi nhận'), ('CANCELLED', 'Đã huỷ')], default='DRAFT', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
