# Generated by Django 5.1.15 on 2026-10-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_purchasereceipt_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasereceipt',
            options={'ordering': ['-received_date', '-id'], 'verbose_name': 'Phiếu nhập', 'verbose_name_plural': 'Phiếu nhập'},
        ),
    ]
