# Generated by Django 5.1.15 on 2026-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Báo cáo lãi lỗ',
                'verbose_name_plural': 'Báo cáo lãi lỗ',
                'permissions': [('view_profitreport', 'Xem báo cáo giá vốn / lãi lỗ')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
