# Generated by Django 5.1.15 on 2026-09-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profitreport',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_profitreport', 'Xem báo cáo giá vốn / lãi lỗ'), ('view_dashboard', 'Xem Tổng quan vận hành')], 'verbose_name': 'Báo cáo lãi lỗ', 'verbose_name_plural': 'Báo cáo lãi lỗ'},
        ),
    ]
