# Generated by Django 5.1.15 on 2026-10-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_view_dashboard_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profitreport',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_profitreport', 'Xem báo cáo lãi lỗ'), ('view_dashboard', 'Xem Tổng quan')], 'verbose_name': 'Báo cáo lãi lỗ', 'verbose_name_plural': 'Báo cáo lãi lỗ'},
        ),
    ]
