# Generated by Django 5.1.15 on 2026-09-13 15:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Tên khách')),
                ('default_address', models.TextField(blank=True, verbose_name='Địa chỉ giao mặc định')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['phone'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Mã hoá đơn')),
                ('issued_at', models.DateTimeField(verbose_name='Thời điểm xuất (xác nhận TT)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Số tiền')),
                ('payment_txn_ref', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch ngân hàng')),
                ('payment_method', models.CharField(default='VIETQR', max_length=32, verbose_name='Kênh thanh toán')),
                ('status', models.CharField(choices=[('ISSUED', 'Đã xuất'), ('CANCELLED', 'Đã huỷ')], default='ISSUED', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Hoá đơn bán',
                'verbose_name_plural': 'Hoá đơn bán',
                'ordering': ['-issued_at', '-id'],
                'permissions': [('confirm_payment_manual', 'Xác nhận thanh toán thủ công')],
                'default_permissions': ('view', 'change'),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Số tiền hoàn')),
                ('is_partial', models.BooleanField(default=False, verbose_name='Hoàn một phần')),
                ('method', models.CharField(choices=[('MANUAL_TRANSFER', 'Chuyển khoản tay'), ('GATEWAY', 'Qua cổng (chưa hiện thực)')], default='MANUAL_TRANSFER', max_length=16, verbose_name='Phương thức')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ hoàn'), ('REFUNDED', 'Đã hoàn'), ('FAILED', 'Thất bại')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('bank_txn_ref', models.CharField(blank=True, help_text='Bắt buộc khi chuyển sang Đã hoàn (BR-HT-03).', max_length=100, verbose_name='Mã giao dịch chuyển khoản')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận hoàn')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo phiếu')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.salesinvoice', verbose_name='Hoá đơn')),
            ],
            options={
                'verbose_name': 'Phiếu hoàn tiền',
                'verbose_name_plural': 'Phiếu hoàn tiền',
                'ordering': ['-created_at', '-id'],
                'permissions': [('create_refund', 'Tạo phiếu hoàn tiền'), ('confirm_refund', 'Xác nhận đã hoàn tiền (tiền rời tài khoản)')],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Số lượng (kg)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Đơn giá (đ/kg)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Thành tiền')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice', verbose_name='Hoá đơn')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item', verbose_name='Mặt hàng')),
            ],
            options={
                'verbose_name': 'Dòng hoá đơn',
                'verbose_name_plural': 'Dòng hoá đơn',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Số kg')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Giá vốn ảnh chụp (đ/kg)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_allocations', to='inventory.batch', verbose_name='Lô')),
                ('component_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item', verbose_name='Mặt hàng thực trừ')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='sales.salesinvoiceline', verbose_name='Dòng hoá đơn')),
            ],
            options={
                'verbose_name': 'Phân bổ lô đã bán',
                'verbose_name_plural': 'Phân bổ lô đã bán',
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Mã đơn')),
                ('status', models.CharField(choices=[('BOOKED', 'Giữ chỗ'), ('PAID', 'Đã thanh toán'), ('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Hoàn tất'), ('CANCELLED', 'Đã huỷ'), ('AUTO_CANCELLED', 'Tự huỷ (quá TTL)')], default='BOOKED', max_length=16, verbose_name='Trạng thái')),
                ('delivery_address', models.TextField(verbose_name='Địa chỉ giao')),
                ('phone', models.CharField(max_length=20, verbose_name='SĐT nhận hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Tổng tiền')),
                ('booked_expires_at', models.DateTimeField(blank=True, help_text="created_at + TTL (mặc định 30') — job nền quét & nhả (BR-BH-03/04).", null=True, verbose_name='Hết hạn giữ chỗ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at', '-id'],
                'permissions': [('cancel_paid_order', 'Huỷ đơn đã thanh toán')],
                'default_permissions': ('view', 'change'),
            },
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.salesorder', verbose_name='Đơn hàng'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_txn_id', models.CharField(max_length=100, unique=True, verbose_name='Mã giao dịch ngân hàng')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Số tiền về')),
                ('match_status', models.CharField(choices=[('MATCHED', 'Khớp — đã xác nhận'), ('UNDERPAID', 'Thiếu tiền — chờ Chủ'), ('ORPHAN', 'Đến sau khi đơn đã huỷ — chờ Chủ'), ('UNMATCHED', 'Không khớp đơn — chờ Chủ')], max_length=12, verbose_name='Kết quả khớp')),
                ('source', models.CharField(choices=[('WEBHOOK', 'Webhook SePay'), ('MANUAL', 'Xác nhận tay')], default='WEBHOOK', max_length=8, verbose_name='Nguồn')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload gốc')),
                ('received_at', models.DateTimeField(verbose_name='Thời điểm nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.salesorder', verbose_name='Đơn khớp')),
            ],
            options={
                'verbose_name': 'Giao dịch thanh toán',
                'verbose_name_plural': 'Giao dịch thanh toán',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Số lượng (kg)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Đơn giá (đ/kg)')),
                ('bundle_snapshot', models.JSONField(blank=True, default=dict, help_text='Công thức BundleLine đóng băng lúc đặt (BR-DM-07).', verbose_name='Ảnh chụp công thức combo')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Giảm giá (đ)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Thành tiền')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item', verbose_name='Mặt hàng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder', verbose_name='Đơn')),
                ('pricing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.pricingrule', verbose_name='Ưu đãi áp dụng')),
            ],
            options={
                'verbose_name': 'Dòng đơn',
                'verbose_name_plural': 'Dòng đơn',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Số kg giữ')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Giá vốn ảnh chụp')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.batch', verbose_name='Lô')),
                ('component_item', models.ForeignKey(help_text='Với BUNDLE là thành phần; với SIMPLE trùng item của dòng.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item', verbose_name='Mặt hàng thực trừ')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='sales.salesorderline', verbose_name='Dòng đơn')),
            ],
            options={
                'verbose_name': 'Giữ chỗ theo lô',
                'verbose_name_plural': 'Giữ chỗ theo lô',
                'default_permissions': ('view',),
            },
        ),
    ]
