# Generated by Django 5.1.15 on 2026-09-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoiceline',
            options={'default_permissions': ('view',), 'verbose_name': 'Dòng hoá đơn', 'verbose_name_plural': 'Dòng hoá đơn'},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={'default_permissions': ('view',), 'verbose_name': 'Dòng đơn', 'verbose_name_plural': 'Dòng đơn'},
        ),
    ]
