# Generated by Django 5.1.15 on 2026-09-25 13:56
"""
Lô L8 — S12, S13 (hồ sơ 2026-09-24-erp-console-noi-that).

- PaymentTransaction.resolution_* (S12, BR-TT-09): hàng chờ lệch phải được Chủ đóng có ghi lại
  người / lúc / cách / ghi chú. `resolution_status` null = giao dịch khớp (không thuộc hàng chờ).
- MatchStatus.OVERPAID (P5, BR-TT-10): tiền về cho đơn đã thanh toán → hàng chờ để Chủ hoàn.
- Refund.sales_invoice nullable + Refund.payment_transaction + ràng buộc đúng-một-trong-hai
  (S13, Q9): hoàn cho khoản tiền chưa từng có hoá đơn.
- Refund.request_id (Q12, dùng ở S13 và S15): chống tạo phiếu trùng khi bấm đúp.

Dữ liệu cũ: giao dịch UNDERPAID/ORPHAN/UNMATCHED hiện có → OPEN (đang treo, BR-TT-09);
MATCHED giữ null. Lùi được (reverse = no-op, các cột bị xoá khi lùi).
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


QUEUE_STATUSES = ("UNDERPAID", "ORPHAN", "UNMATCHED")


def open_existing_mismatches(apps, schema_editor):
    PaymentTransaction = apps.get_model("sales", "PaymentTransaction")
    PaymentTransaction.objects.filter(match_status__in=QUEUE_STATUSES).update(resolution_status="OPEN")


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesinvoiceline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='resolution',
            field=models.CharField(blank=True, choices=[('ATTACHED', 'Gắn vào đơn'), ('CONFIRMED', 'Xác nhận đơn (khách đã bù)'), ('REFUNDED', 'Đã hoàn tiền')], default='', max_length=10, verbose_name='Cách xử lý'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='resolution_note',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú xử lý'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='resolution_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Chờ xử lý'), ('RESOLVED', 'Đã xử lý')], db_index=True, help_text='Để trống = giao dịch khớp, không cần xử lý.', max_length=8, null=True, verbose_name='Xử lý lệch'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xử lý'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.paymenttransaction', verbose_name='Giao dịch thanh toán (không hoá đơn)'),
        ),
        migrations.AddField(
            model_name='refund',
            name='request_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Mã yêu cầu (chống trùng)'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='match_status',
            field=models.CharField(choices=[('MATCHED', 'Khớp — đã xác nhận'), ('UNDERPAID', 'Thiếu tiền — chờ Chủ'), ('ORPHAN', 'Đến sau khi đơn đã huỷ — chờ Chủ'), ('UNMATCHED', 'Không khớp đơn — chờ Chủ'), ('OVERPAID', 'Chuyển thừa — đơn đã thanh toán, chờ Chủ')], max_length=12, verbose_name='Kết quả khớp'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.salesinvoice', verbose_name='Hoá đơn'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_transaction__isnull', True), ('sales_invoice__isnull', False)), models.Q(('payment_transaction__isnull', False), ('sales_invoice__isnull', True)), _connector='OR'), name='refund_exactly_one_source'),
        ),
        migrations.RunPython(open_existing_mismatches, migrations.RunPython.noop),
    ]
