# Generated by Django 5.1.15 on 2026-09-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_payment_resolution_refund_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='failure_reason',
            field=models.TextField(blank=True, default='', verbose_name='Lý do thất bại'),
        ),
    ]
