# Generated by Django 5.1.15 on 2026-09-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_refund_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='duplicate_warning',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cảnh báo nghi trùng'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='environment',
            field=models.CharField(blank=True, choices=[('SANDBOX', 'Sandbox (thử)'), ('PRODUCTION', 'Production (thật)')], default='', max_length=10, verbose_name='Môi trường cổng'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='source',
            field=models.CharField(choices=[('WEBHOOK', 'Webhook SePay'), ('MANUAL', 'Xác nhận tay'), ('GATEWAY', 'Cổng SePay')], default='WEBHOOK', max_length=8, verbose_name='Nguồn'),
        ),
    ]
