# Generated by Django 5.1.15 on 2026-09-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_paymenttransaction_duplicate_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='checkout_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần lập tham số thanh toán cổng'),
        ),
    ]
