# Generated by Django 5.1.15 on 2026-09-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_grant_content_perms'),
        ('sales', '0007_alter_refund_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Đồng ý xử lý dữ liệu lúc'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='privacy_policy_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.entryversion', verbose_name='Phiên bản chính sách bảo mật đã đồng ý'),
        ),
    ]
