# Generated by Django 5.1.15 on 2026-09-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesorder_privacy_consent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'default_permissions': ('view', 'change'), 'ordering': ['-created_at', '-id'], 'permissions': [('cancel_paid_order', 'Huỷ đơn đã thanh toán'), ('view_privacy_consent', 'Xem bằng chứng đồng ý xử lý dữ liệu của đơn')], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
    ]
