# Generated by Django 5.1.15 on 2026-09-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_batch_options'),
        ('sales', '0010_grant_view_privacy_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã chứng từ')),
                ('source_key', models.CharField(max_length=64, unique=True, verbose_name='Khoá nguồn (chống trùng)')),
                ('kind', models.CharField(choices=[('CANCEL_ORDER', 'Huỷ đơn đã thanh toán')], default='CANCEL_ORDER', max_length=16)),
                ('issued_at', models.DateTimeField(verbose_name='Thời điểm ghi nhận (kỳ đảo)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Số tiền đảo')),
                ('stock_restored', models.BooleanField(verbose_name='Đã hoàn kho lúc huỷ')),
                ('reason_code', models.CharField(blank=True, max_length=32, verbose_name='Mã lý do huỷ')),
                ('backfilled', models.BooleanField(default=False, verbose_name='Lập bù (SR-14)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người huỷ (trống = Hệ thống)')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.salesinvoice', verbose_name='Hoá đơn gốc')),
            ],
            options={
                'verbose_name': 'Chứng từ đảo doanh thu',
                'verbose_name_plural': 'Chứng từ đảo doanh thu',
                'ordering': ['-issued_at', '-id'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='SalesCreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Số kg đảo')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Đơn giá bán (đ/kg)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Thành tiền đảo')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Giá vốn ảnh chụp (đ/kg)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_lines', to='inventory.batch', verbose_name='Lô')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salescreditnote', verbose_name='Chứng từ')),
                ('invoice_line_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.salesinvoicelinebatch', verbose_name='Phân bổ lô gốc')),
            ],
            options={
                'verbose_name': 'Dòng chứng từ đảo',
                'verbose_name_plural': 'Dòng chứng từ đảo',
                'default_permissions': ('view',),
            },
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['issued_at'], name='sales_sales_issued__d6f3a9_idx'),
        ),
    ]
