# Generated by Django 5.1.15 on 2026-10-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_salescreditnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['phone'], 'permissions': [('view_customer_list', 'Xem khách hàng')], 'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
    ]
