# Generated by Django 5.1.15 on 2026-10-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_grant_view_customer_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='cancel_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ghi chú huỷ đơn'),
        ),
    ]
