# Generated by Django 5.1.15 on 2026-10-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_grant_view_order_customer_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-received_at', '-id'], 'verbose_name': 'Khoản tiền về', 'verbose_name_plural': 'Khoản tiền về'},
        ),
        migrations.AlterModelOptions(
            name='salescreditnote',
            options={'default_permissions': ('view',), 'ordering': ['-issued_at', '-id'], 'verbose_name': 'Phiếu trừ doanh thu', 'verbose_name_plural': 'Phiếu trừ doanh thu'},
        ),
        migrations.AlterModelOptions(
            name='salescreditnoteline',
            options={'default_permissions': ('view',), 'verbose_name': 'Dòng phiếu trừ doanh thu', 'verbose_name_plural': 'Dòng phiếu trừ doanh thu'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'default_permissions': ('view', 'change'), 'ordering': ['-issued_at', '-id'], 'permissions': [('confirm_payment_manual', 'Xác nhận đã nhận tiền')], 'verbose_name': 'Hoá đơn bán', 'verbose_name_plural': 'Hoá đơn bán'},
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='environment',
            field=models.CharField(blank=True, choices=[('SANDBOX', 'Chạy thử'), ('PRODUCTION', 'Chạy thật')], default='', max_length=10, verbose_name='Môi trường cổng'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='match_status',
            field=models.CharField(choices=[('MATCHED', 'Khớp đơn'), ('UNDERPAID', 'Chuyển thiếu'), ('ORPHAN', 'Về sau khi đơn đã huỷ'), ('UNMATCHED', 'Không khớp đơn'), ('OVERPAID', 'Chuyển thừa')], max_length=12, verbose_name='Kết quả khớp'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='resolution',
            field=models.CharField(blank=True, choices=[('ATTACHED', 'Đã gắn vào đơn'), ('CONFIRMED', 'Đã xác nhận đơn'), ('REFUNDED', 'Đã hoàn tiền')], default='', max_length=10, verbose_name='Cách xử lý'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='source',
            field=models.CharField(choices=[('WEBHOOK', 'Ngân hàng báo'), ('MANUAL', 'Xác nhận tay'), ('GATEWAY', 'Cổng SePay')], default='WEBHOOK', max_length=8, verbose_name='Nguồn'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='method',
            field=models.CharField(choices=[('MANUAL_TRANSFER', 'Chuyển khoản tay'), ('GATEWAY', 'Qua cổng SePay')], default='MANUAL_TRANSFER', max_length=16, verbose_name='Phương thức'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.paymenttransaction', verbose_name='Khoản tiền về (không hoá đơn)'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ hoàn tiền'), ('REFUNDED', 'Đã hoàn tiền'), ('FAILED', 'Hoàn thất bại')], default='PENDING', max_length=10, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Giữ chỗ'), ('PAID', 'Đã thanh toán'), ('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Hoàn tất'), ('CANCELLED', 'Đã huỷ'), ('AUTO_CANCELLED', 'Hết giờ giữ chỗ')], default='BOOKED', max_length=16, verbose_name='Trạng thái'),
        ),
    ]
