# Generated by Django 5.1.15 on 2026-10-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('create_refund', 'Lập phiếu hoàn tiền'), ('confirm_refund', 'Xác nhận đã hoàn tiền (tiền rời tài khoản)')], 'verbose_name': 'Phiếu hoàn tiền', 'verbose_name_plural': 'Phiếu hoàn tiền'},
        ),
    ]
