# Generated by Django 5.1.15 on 2026-10-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_refund_create_permission_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'default_permissions': ('view', 'change'), 'ordering': ['-created_at', '-id'], 'permissions': [('cancel_paid_order', 'Huỷ đơn đã thanh toán'), ('view_privacy_consent', 'Xem bằng chứng đồng ý xử lý dữ liệu của đơn'), ('view_order_customer_info', 'Xem thông tin khách trên đơn, hoá đơn, phiếu hoàn tiền')], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
    ]
