# Generated by Django 5.1.15 on 2026-10-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_salesorder_view_order_customer_info_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='client_request_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Mã yêu cầu tạo đơn (chống trùng)'),
        ),
    ]
